name: Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

permissions:
  id-token: write
  contents: read
  checks: write

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      -
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
              node-version: 16

      - name: Install junit merge
        run: npm install -g junit-merge

      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'
#      - name: Build & Install
#        run: mvn -B install -D skipTests --no-transfer-progress
      - name: Ensure browsers are installed
        run: mvn exec:java -e -D exec.mainClass=com.microsoft.playwright.CLI -D exec.args="install --with-deps"
      - name: Run tests
        run: mvn clean test

      - name: Merge junit xml reports
        run: junit-merge  -o results.xml -d target/surefire-reports/junitreports/

      - name: Test Report
        uses: dorny/test-reporter@v1
        if: success() || failure()    # run this step even if previous step failed
        with:
            name: Playwright Tests            # Name of the check run which will be created
            path: results.xml   # Path to test results
            reporter: java-junit